### ISSUE TITLE
Wrong app version and docker images tag 

### ISSUE THREAD

**Issue by egbakou** [JetBrains/datalore-configs#23]
I get this error when trying to install Datalore using the [docker-compose ](https://github.com/JetBrains/datalore-configs/blob/main/docker-compose/docker-compose.yaml)file.
```
➜ docker compose up
[+] Running 0/2
 - datalore Error                                                                              4.8s
 - postgresql Error                                                                            4.8s
Error response from daemon: manifest for jetbrains/datalore-postgres:2022.3 not found: manifest unknown: manifest unknown
```

The error is caused by the commit https://github.com/JetBrains/datalore-configs/commit/f4041f302ef82d50f27d09677e45d40d3864aa55

I submitted a PR : https://github.com/JetBrains/datalore-configs/pull/24

**Comment by alexandrvb** [comment]
Hello @egbakou 
2022.3 has not released yet. Please use 2022.2.3 branch with the latest Datalore release.

I've also changed default branch to 2022.2.3
