### ISSUE TITLE
ingress labels not compatible with RKE2-style kubernetes versio

### ISSUE THREAD

**Issue by stephanbertl** [JetBrains/datalore-configs#31]
There is an issue with the ingress template of datalore located at https://github.com/JetBrains/datalore-configs/blob/1069a97e1006a2a4da45f66277c0ded0834c89f9/charts/datalore/templates/ingress.yaml#L21C1-L22C1

`ver: {{ .Capabilities.KubeVersion.GitVersion }}`

When using Rancher Kubernetes with RKE2, the version of Kubernetes is:

`"v1.25.13+rke2r1"`

Using that value, helm cannot create the ingress because

Error: INSTALLATION FAILED: 1 error occurred:
        * Ingress.extensions "datalore" is invalid: metadata.labels: Invalid value: "v1.25.13+rke2r1": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

**Comment by alexandrvb** [comment]
@stephanbertl thank you, I've deleted the label
